// generated by stringer -type comicType temp.go; DO NOT EDIT

package redshift

import "fmt"

const _comicType_name = "InvalidComicMangaManhwaManhuaWesternWebcomicOther"

var _comicType_index = [...]uint8{12, 17, 23, 29, 36, 44, 49}

func (i comicType) String() string {
	if i < 0 || i >= comicType(len(_comicType_index)) {
		return fmt.Sprintf("comicType(%d)", i)
	}
	hi := _comicType_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _comicType_index[i-1]
	}
	return _comicType_name[lo:hi]
}
