// generated by stringer -type comicStatus temp.go; DO NOT EDIT

package redshift

import "fmt"

const _comicStatus_name = "ComicStatusInvalidComicCompleteComicOngoingComicOnHiatusComicDiscontinued"

var _comicStatus_index = [...]uint8{18, 31, 43, 56, 73}

func (i comicStatus) String() string {
	if i < 0 || i >= comicStatus(len(_comicStatus_index)) {
		return fmt.Sprintf("comicStatus(%d)", i)
	}
	hi := _comicStatus_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _comicStatus_index[i-1]
	}
	return _comicStatus_name[lo:hi]
}
