#include "cpp/qcapi.cpp"
#include "cpp/updatemodel.cpp"
#include "cpp/moc_updatemodel.cpp"
#include "cpp/infomodel.cpp"
#include "cpp/moc_infomodel.cpp"
#include "cpp/chaptermodel.cpp"
#include "cpp/moc_chaptermodel.cpp"
